### ISSUE TITLE
System.MissingMethodException : Method not found: 'Splat.IDependencyResolver Splat.Locator.get_Current()'.

### ISSUE THREAD

**Issue by j-fritsch** [ryanwersal/AutoSplat#10]
After updating to Splat 9.0.5, I am now seeing the following exception:
```
System.MissingMethodException : Method not found: 'Splat.IDependencyResolver Splat.Locator.get_Current()'.
   at AutoSplat.AutoMockContext..ctor()
```
I believe this is due to a change in Splat in how you set the current `Locator`. You now have to call `SetLocator`: https://github.com/reactiveui/splat/commit/01b2beb2fa7e7ba983970cfcf469faed96d49d2f

**Comment by ryanwersal** [comment]
@j-fritsch Could you give [the preview of v9](https://www.nuget.org/packages/AutoSplat/9.0.0-preview-20191006.2) a try and see if that fixes your issue and doesn't cause other issues? Thanks!

**Comment by j-fritsch** [comment]
I will try this out as soon as possible. Turns out ReactiveUI/Splat caused some other, non-AutoSplat related issues that caused us to revert for now. I appreciate you taking a look at this so quickly!

**Comment by j-fritsch** [comment]
@ryanwersal, looks like the issue has been resolved. Thanks again!

**Comment by ryanwersal** [comment]
@j-fritsch Version 9.0.0 is released on NuGet. Thanks for testing!
